### ISSUE TITLE
possible bug in completion style for repeated pattern

### ISSUE THREAD

**Issue by gtusr** [oantolin/orderless#129] opened 2023-01-10 22:16 UTC
From the description of the orderless filtering algorithm, I would expect that

`M-x fi SPC fi` 

should bring up 'find-file' command as the first choice.  It appears, however, that the two 'fi' patterns match the 'fi' in the word 'find' one on top of the other, by observing how the syntax highlighting changes.  As a result, the total number of choices does not change after processing the second 'fi' pattern.

Is this the correct behavior?

**Comment by oantolin** [comment] 2023-01-11 04:22
That is the expected behavior. Orderless splits the input into components, compile each to a regexp, and a string if considered to match if each component's regexp matches somewhere in the string. In particular it follows that repeating components makes no difference to whether a string matches or not.

For the particular example of matching something like `fi fi` to `find-file`, I'd suggest using the `orderless-prefixes` matching style and phrasing the input as `fi-fi` instead. Or you could use the `orderless-regexp` style and type `fi.*fi`.

**Comment by minad** [comment] 2023-01-11 06:22
I wonder if it makes sense to add a special rule which compiles repeated patterns to literals separated by `.*`.

Alternatively one could combine all the styles but I don't think the quadratic, cubic behavior, etc  would be a great idea.

**Comment by oantolin** [comment] 2023-01-11 06:28
Even if we added that special rule, I'd still use `fi-fi` with `orderless-prefixes` for this example, because it matches fewer things as it means `\<fi.*-fi`. I think I'm happy with being precise about whether I mean `\<fi.*-fi` or just `fi.*fi` specially since I get to pick the syntax for those things. I've never found much use for `fi.*fi` so I don't mind typing two characters (`.` and `*`) to get that meaning, and I do have `orderless-prefixes` setup for components with dashes or a few other separators in them.

**Comment by oantolin** [comment] 2023-01-11 06:55
We don't need that special rule since it is easy to do in your own configuration:

```elisp
(defun respect-repeats (string)
  (mapcar
   (lambda (group) (string-join (cdr group) ".*"))
   (seq-group-by #'identity (split-string string))))

(setq orderless-component-separator #'respect-repeats)
```

**Comment by oantolin** [comment] 2023-01-11 06:56
I'm closing this since I think this should be handled in configuration like in the above example code.

**Closed by oantolin** 2023-01-11 06:56 UTC

**Comment by minad** [comment] 2023-01-11 06:59
Makes sense. It is just that users seem to often stumble over this
issue. What about compiling repeated patterns to prefix syntax then? I
think typing `fi-fi` vs `fi fi` still adds a little bit of mental
overhead, since Orderless is relying so much on SPC. It would be an
optional feature, which probably wouldn't add much complexity and
wouldn't lead to a muddying of the overall character of Orderless.

If you would be willing to add this one should check that other issues
related to repeated patterns would be fixed. Iirc there was also a
proposal that repeated patterns should somehow affect the ordering,
which is obviously not a possibility.

**Comment by minad** [comment] 2023-01-11 07:01
On 1/11/23 07:56, Omar Antolín Camarena wrote:
> We don't need that special rule since it is easy to do in your own
> configuration:
> 
> (defun respect-repeats (string)
>   (mapcar
>    (lambda (group) (string-join (cdr group) ".*"))
>    (seq-group-by #'identity (split-string string))))
> 
> (setq orderless-component-separator #'respect-repeats)

Oh, I see. That's very nice. So the only thing left then could be that
we add this special separator to Orderless then. That's even less
intrusive than I had expected. But keeping this in a user configuration
or the wiki is fine too.

**Comment by gtusr** [comment] 2023-01-11 10:36
Thanks for the explanation and a proposed solution by treating the repeated pattern as a special case that needs to use `.*` in order to concatenate the two terms.

But I think the problem is more general than this.  Some users may naturally think in terms of the matches to the sequence of pattern components separated by spaces as being 'consumed' by the matching algorithm in some order, so that in the case of the OP, the first 'fi' in find-file would match, and then remove from further consideration, the fi in 'find', leaving just 'nd-file' for the second 'fi' to match.  

Viewed from this perspective, the issue is no longer just about repeated pattern components.

Is there an easy way to configure orderless so that the matches to the individual pattern components cannot overlap in a successful candidate?

**Comment by oantolin** [comment] 2023-01-11 14:40
Well, programs in the "machine language" that orderless compiles to are just list of regexps and the semantics are that a string matches the list if every regexp matches. Which is why orderless's semantics is chosen to be similar: input matches if each component matches according to the chosen styles.

But I think it's not too hard to do an alternative component separator where something like `ab bc ef` compiles to the list `("ab.*bc\|bc.*ab" "ef")`. I'll try my hand at it when I get the chance.

**Comment by bkchr** [comment] 2023-03-31 21:23
@oantolin you did not by accident got some time to try this out?

**Comment by oantolin** [comment] 2023-04-01 21:09
I had completely forgotten about this @bkchr. But it's easy, the idea is to split the input on spaces, then group the components so that any two components whose matches might overlap are in the same group, and then for each group create a regexp that matches them in any order by joining all the permutations with `.*`s. Here's a [quick implementation](https://gist.github.com/oantolin/867e999c3067bff2059365487b6873d2), which is probably easy to improve.

With the functions in that gist you could set `orderless-component-separator` to `consumptive-components` and `orderless-matching-styles` to `'(orderless-regexp)`. With further effort one could support other matching styles, but that version is meant to be used exclusively with `orderless-regexp`.

**Comment by bkchr** [comment] 2023-04-01 23:16
Nice ty @oantolin :)
