### ISSUE TITLE
Multiple matches, and/or over specifying candidates

### ISSUE THREAD

**Issue by sienic** [oantolin/orderless#125] opened 2022-09-29 19:39 UTC
Hey there,
let's say I have a buffer which happens to have the same name as the folder:

```
aService/aService.ext
```

Is there such thing as a "scoring", in which a component that matches more than once, gets precedence?

Or, is there such thing that whenever we repeat a component e.g. `aS aS`, candidates matching the amount of components get precedence?

Thanks.

Happy to contribute with a solution for this if it doesn't exist (which brings another question: which approach you think it would be more feasible/straight forward?).

**Comment by minad** [comment] 2022-09-29 21:01
This is not possible by design since Orderless doesn't sort the candidates. Maybe you are interested in the `flex` completion style or https://github.com/jojojames/fussy, which can use Orderless as filter backend.

**Comment by oantolin** [comment] 2022-09-29 22:55
As @minad said, orderless does no sorting at all, so something like this is out of scope.

**Closed by oantolin** 2022-09-29 22:55 UTC
