### ISSUE TITLE
Possible conflict between orderless and AUCTeX

### ISSUE THREAD

**Issue by kourosh2** [oantolin/orderless#148] opened 2023-10-24 12:27 UTC
Hi all, 

I am encountering an issue when using the `orderless` package alongside `AUCTeX` in Emacs. My configuration for `orderless` is set to globally apply its completion style. However, when I am working within an `AUCTeX` buffer and utilize the macro completion does not work properly, for example in `\includegraphics` macro completion, the `width` field is being duplicated, resulting in `width=width=\linewidth` instead of the expected `width=\linewidth`. This duplication occurs only when the `orderless` completion style is active; disabling `orderless` resolves the duplication issue. I attempted to set the completion-styles locally for AUCTeX buffers to bypass this problem, but the orderless completion style persists. I don't know whether this is a bug or a problem unique to my configuration.  Any help is appreciated. 

Thanks, 
Kourosh

Below is my Emacs, `orderless` and `AUCTeX` versions:
- GNU Emacs 29.1 (build 2, x86_64-apple-darwin23.0.0, NS appkit-2487.00 Version 14.0 (Build 23A344)) of 2023-10-02
- AUCTeX Version 13.2.2
- Orderless Version 20230920.553

**Comment by oantolin** [comment] 2023-10-24 12:35
I just realized I don't really take full advantage of completion in AUCTeX: I know how to get it to complete the macro name `\includegraphics`, but how you get it to complete the `width` parameter? Literally: what did you type to see that behavior?

**Comment by kourosh2** [comment] 2023-10-24 12:43
I do `C-c RET` followed by the macro name, in this case `\includegraphics`, and then AUCTeX asks for options (see screenshots) at which I start typing width and then tab to complete.  

![Screenshot 2023-10-24 at 08 40 16](https://github.com/oantolin/orderless/assets/19352417/46f9d29c-8a84-4d00-9772-8632f870e478)
![Screenshot 2023-10-24 at 08 41 59](https://github.com/oantolin/orderless/assets/19352417/4d0f3cc6-0b94-4b1e-b4e7-287cc9da6cf3)

**Comment by oantolin** [comment] 2023-10-24 13:22
Thanks! Now I will attempt to reproduce.

**Comment by oantolin** [comment] 2023-10-24 13:37
Yep, I can reproduce it now, and it doesn't happen with `basic`, `substring` or `flex`, so it probably is `orderless`'s fault. I'll look into it.

**Comment by kourosh2** [comment] 2023-10-24 13:55
Great, appreciate it. 

Kourosh

**Comment by minad** [comment] 2023-10-24 13:59
Just speculating, but this could maybe happen due to our optimized try-completion implementation.

How did you test flex or substring? Did you set completion-styles to (basic flex) or (flex basic)?

I think the issue can be resolved in many cases by using (basic orderless) instead of (orderless basic).

**Comment by oantolin** [comment] 2023-10-24 14:03
> How did you test flex or substring? Did you set completion-styles to (basic flex) or (flex basic)?

No, just `(flex)`.

**Comment by oantolin** [comment] 2023-10-24 14:06
I don't think the problem is in the optimization abusing the predicate. The issue seems to be whether in the case of a unique completion you should include concatenate the prefix onto the unique completion or not. Orderless does that because otherwise completing a filename you'd lose the path, but here you get a duplication. I'm currently trying to understand what the built-in styles due to work in both cases.

**Comment by oantolin** [comment] 2023-10-24 14:34
I'm very confused. If I'm reading `minibuffer.el` correctly, you are supposed to concatenate the prefix. Weird.

**Comment by oantolin** [comment] 2023-10-25 02:00
@minad asked:

> Do you have an isolated completion table at hand which demonstrates the problem with orderless and works with substring?

After tracing through AUCTeX's many functions for a while I finally found it uses the interesting non-AUCTeX function `multi-prompt-key-value`, which I was not familiar with.
It sets up a `minibuffer-completion-table` and calls `read-from-minibuffer`.

Here's a small example that works with `basic`, `substring`, `partial-completion` or `flex` but has that funny duplication if you use `orderless`:

```elisp
(let ((completion-styles '(substring)))
  (multi-prompt-key-value
   "k=v pairs: "
   '(("ab" ("op1" "ch2" "se3"))
     ("cd" ("op2" "ch3" "se1")))))
```

**Comment by minad** [comment] 2023-10-25 03:24
multi-prompt is part of auctex: https://github.com/emacsmirror/auctex/blob/master/multi-prompt.el. The function is a bit dubious also since it doesn't go through completing-read. It is not obvious where the difference lies, such that substring doesn't add the prefix.

**Comment by oantolin** [comment] 2023-10-25 03:30
> multi-prompt is part of auctex

Ha, so it is! Thanks for the correction.

> The function is a bit dubious also since it doesn't go through completing-read. 

Yeah, it's adapted from crm, but crm does use completing-read.

**Comment by minad** [comment] 2023-10-25 19:31
I've analyzed the problem a little bit. As I had initially speculated, the problem is related to our try completion optimization. But I am not sure if the bug is in `orderless-try-completion` or in `completion-table-with-context`. 

The context table adds a prefix before calling the predicate, see https://github.com/emacs-mirror/emacs/blob/ccaf801baad95f470e9806e075a15a18eb216a54/lisp/minibuffer.el#L321. We take the argument passed to the predicate and return it with the prefix concatenated.

In contrast, the file completion table does not add the prefix to the predicate. This can be tested easily:

~~~ elisp
(completing-read "Prompt: "
                 #'completion-file-name-table
                 (lambda (file)
                   (message "PREDICATE %S" file)
                   t))
~~~

In both cases, for the file name completion table and the completion table with context, the boundaries are correctly reported. But the two tables differ in their behavior with respect to the predicate. It seems that `completion-table-with-context` should probably not add the prefix before calling the predicate. This problem was introduced a long time ago in https://github.com/emacs-mirror/emacs/commit/25c0d999666985929f375a75f4ed5018b7c5e9f3.

**Comment by minad** [comment] 2023-10-25 19:34
For reference, here is the code of `completion-table-with-context`:

~~~ elisp
(defun completion-table-with-context (prefix table string pred action)
  ;; TODO: add `suffix' maybe?
  (let ((pred
         (if (not (functionp pred))
             ;; Notice that `pred' may not be a function in some abusive cases.
             pred
           ;; Predicates are called differently depending on the nature of
           ;; the completion table :-(
           (cond
            ((vectorp table)            ;Obarray.
             (lambda (sym) (funcall pred (concat prefix (symbol-name sym)))))
            ((hash-table-p table)
             (lambda (s _v) (funcall pred (concat prefix s))))
            ((functionp table)
             (lambda (s) (funcall pred (concat prefix s))))
            (t                          ;Lists and alists.
             (lambda (s)
               (funcall pred (concat prefix (if (consp s) (car s) s)))))))))
    (if (eq (car-safe action) 'boundaries)
        (let* ((len (length prefix))
               (bound (completion-boundaries string table pred (cdr action))))
          `(boundaries ,(+ (car bound) len) . ,(cdr bound)))
      (let ((comp (complete-with-action action table string pred)))
        (cond
         ;; In case of try-completion, add the prefix.
         ((stringp comp) (concat prefix comp))
         (t comp))))))
~~~

**Comment by minad** [comment] 2023-10-25 19:51
On the other hand, the caller of completing-read controls both predicate and table from outside. As such, both choices could be reasonable - the predicate called without prefix (1) or with predicate (1). The problem arises in the case of Orderless which as a completion style (or middleware) sits in between the outer caller and the inner completion table. 

My assumption is still that the candidate strings returned by `all-completions` shuld match the the strings passed to the predicate. This assumption makes sense since this way a completion style can use both `completion-regexp-list` and the predicate consistently. This assumption is violated by `completion-table-with-context`, where the candidates without prefix are matched against the regexps and the predicate receives prefixed candidates.

**Comment by minad** [comment] 2023-10-25 20:18
I've looked at `file-name-completion` and `file-name-all-completions`, low level functions sitting below `completion-file-name-table`. Interestingly only `file-name-completion` takes an optional predicate argument, which according to the docstring should receive a candidate in *absolute form* (with prefix, I would guess?) but actually receives only the file name without prefix. Since the predicate is not handled by `file-name-all-completions`, the handling is instead done in a loop in `completion-file-name-table`.

The docstring of `all-completions` is unfortunately not clear about the values received by the predicate. I would read between the lines that the return values are likely the same values as passed to the predicate.

Then I've found another function `completion-table-subvert` which performs prefix substitution of completion tables. The predicate is left untouched here, no prefix substitution is performed, which is inconsistent with `completion-table-with-context`.

I propose to maybe report the inconsistency of `completion-table-with-context` via report-emacs-bug and add a workaround to `orderless-try-completion`.

**Closed** 2023-10-25 23:21 UTC

**Comment by oantolin** [comment] 2023-10-25 23:24
Thank you, so much, @minad! I agree with your analysis and workaround. It's the workaround I was thinking of doing anyway, but I hadn't gone through the process of figuring out why the problem happened in the first place, so I wasn't sure the workaround was really sensible. Did you report the inconsistency of `completion-table-with-context`?

**Comment by minad** [comment] 2023-10-26 05:12
No, I didn't report this yet. Maybe Stefan @monnier is interested in this discussion, since he wrote completion-table-with-context? Stefan, is the prefixing of the string intended when calling the predicate? If yes, why is that?

**Comment by monnier** [comment] 2023-10-26 14:15
> No, I didn't report this yet. Maybe Stefan @monnier is interested in this
> discussion, since he wrote completion-table-with-context? Stefan, is the
> prefixing of the string intended when calling the predicate?

Yes, it's definitely intended (as evidenced by the amount of work done
for it in the code :-)

> If yes, why is that?

Because the predicate applies to "the things we're completing" and those
things do have the prefix.  `all-completions` doesn't add the prefix
because `all-completions` generally wants to return shorter strings that
concentrate on the "relevant" part that is different between the various
completions, but that's at the cost of needing to interpret these
strings "in context".  In general, the predicate can't know what that
context is (i.e. what the prefix is, here) since it can change depending
on the string on which the completion is performed.

> My assumption is still that the candidate strings returned by
> all-completions should match the the strings passed to the predicate

Think of the case where we're completing files and we use
`file-directory-p` as predicate: clearly, we need to pas the "full" file
name, including leading directories otherwise `file-directory-p` will
not know in which directories to look.


        Stefan

**Comment by oantolin** [comment] 2023-10-26 14:19
> Think of the case where we're completing files and we use `file-directory-p` as predicate: clearly, we need to pas the "full" file name, including leading directories otherwise `file-directory-p` will not know in which directories to look.

But in that case, if I understand my own tests and @minad's report correctly, the prefix is *not* included in the string passed to the predicate, @monnier!

**Comment by monnier** [comment] 2023-10-26 14:43
Sigh, yes, there's the theory and then there's the practice: the file-name completion table changes `default-directory` instead of adding the prefix, for efficiency reasons.  `completion-table-with-context` can't use such a trick.

**Comment by minad** [comment] 2023-10-26 15:00
@monnier Okay, I think it would be better and more consistent to only pass the unprefixed candidate to the predicate. From what I've seen completion-table-with-context is the only exception. Are there more? But anyway, as usual it is too late to change this.

**Comment by monnier** [comment] 2023-10-26 15:01
BTW, this is not the only wrinkle in my story.  E.g. when you call `read-file-name` with a predicate of `file-directory-p` you have fundamentally a problem because `read-file-name` doesn't actually read just string which denote file names but instead it reads strings which *after envvar-substitution* denote file names.  Yet, `file-directory-p` won't apply envvar substitution to its argument.  So in theory for a file named `foo$bar` the completion machinery should call the predicate with `foo$$bar` but the predicate won't treat it as intended :-(

**Comment by monnier** [comment] 2023-10-26 15:15
@minad: In theory, `completion-table-with-context` in the only place where the question can arise.  So from that standpoint, I'd say that it's the file-name completion table which is the exception (because it doesn't use `completion-table-with-context` like it "should").
It's a quite messy area, I'm afraid.  When working on the `completion-styles` thingy, I tried to straighten things out somewhat, but failed in numerous ways.  The handling of predicates is definitely a sore point.

To go back to the `read-file-name with a predicate of `file-directory-p`, I think what's really going on is that the file-name completion table is a layering `completion--embedded-envvar-table` and `completion--file-name-table` and we'd like `read-file-name` be able to say that the predicate applies to the underlying `completion--file-name-table` and not to the overall completion table.  But instead this problem is "solved" by making `completion--embedded-envvar-table` presume that the predicate is always meant for the underlying `completion--file-name-table` (i.e. it passes `pred` as is to it and it just ignores `pred` altogether when completing envvar names).

**Comment by minad** [comment] 2023-10-26 15:29
@monnier I believe the historical mistake is that the predicate and
table are separate entities. If the predicate would be transformed
together with the table, such problem could probably be worked around
more easily. For example the predicate could be part of the table
metadata. Confusingly the completion-metadata function also takes a
predicate argument, but this might just be there to satisfy the calling
convention?

**Comment by minad** [comment] 2023-10-26 15:34
On the other hand the predicate is also meant to be changed separately from the table. What I mean is that the predicate and the table should be somehow transformed together consistently, such that such layering issues can be avoided where the table and the predicate layers don't match.

**Comment by monnier** [comment] 2023-10-26 15:43
@minad: Yes, exactly.  For example `minibuffer-completion-table` should not exist.  Instead the predicate
should be included in the completion table (e.g. with something like `completion-table-with-predicate`), so it can be added at the appropriate level.
[ And yes, the `completion-metadata` shouldn't take a predicate argument.  ]
