### ISSUE TITLE
Request/suggestion: support ^-prefix and $-suffix to STRICT leading and ending initialisms

### ISSUE THREAD

**Issue by dalanicolai** [oantolin/orderless#85] opened 2021-10-05 13:07 UTC
First of all, thanks for your work. Your project(s) look very interesting.

I am an Ivy and Spacemacs user. In Spacemacs, Ivy opens with the `^` as initial-input by default. It means that we want to match from the beginning of some expression. If we don't want to match the beginning, we simply remove the ^ with backspace or, as a better alternative, just insert a `SPC` first. Also in Spacemacs `M-x` is mapped to `SPC SPC` so if we do not want to match from beginning we just type triple space.

Anyway, I would suggest that orderless offers the option to insert a ^ by default, and furthermore, the option to indicate when using initialisms, by pre-/suf-fixing the first and last characters that they should match the initials of the first and last words (if it should not match the first initial than we could insert a `SPC` first).

I hope my explanation is clear enough, and that you find it a useful suggestion (of course this is just taken from Ivy).

**Comment by dalanicolai** [comment] 2021-10-05 13:22
Here is a video
- I first type `SPC` twice
- then I type `SPC` three times
- subsequently I ad `pe`
- and finally I add the $ to tell 'pe' should match the final part
![output-2021-10-05-15:16:39](https://user-images.githubusercontent.com/18429791/136031253-6eeeb288-b410-4f56-aec0-ab0c5e3fb0fd.gif)

**Comment by minad** [comment] 2021-10-05 19:22
I am not sure I understand you fully here, but orderless style dispatchers allow at least to prefix the first component with "^". In Orderless almost nothing is hard coded, the user should write their own style dispatchers and configure the desired matching styles (initialism etc).

**Comment by minad** [comment] 2021-10-05 19:24
Maybe the style dispatchers I am using are helpful for your use case: https://github.com/minad/consult/wiki#orderless-style-dispatchers-ensure-that-the--regexp-works-with-consult-buffer

**Comment by oantolin** [comment] 2021-10-06 22:43
Oh, I see. Well `^` and `$` can't really express whether an intialism matches strictly or not. "Strictly" means you are not allowed to skip any words. For example, I said `cur` matches `comment-or-uncomment-region` as an initialism but it does not match as a strict initialism because we skipped the word `or`. So you can't replace the strict styles by expanding `orderless-initialism` to allow anchors.

Of course, you may want the anchor extension anyway, even if it does not replace the strict initialism matching styles.

**Comment by oantolin** [comment] 2021-10-06 22:48
Yes, and it is fairly easy to do. A matching style is a function that takes a string and returns a regexp. Here you can leverage `orderless-initialism` for the middle part and just handle any initial `^` or final `$`:

```elisp
(defun orderless-anchorable-initialism (pattern)
  (concat
   (if (string-prefix-p "^" pattern) "^" "")
   (orderless-initialism
    (string-remove-prefix "^" (string-remove-suffix "$" pattern)))
   (if (string-suffix-p "$" pattern) "[A-Za-z0-9]*$" "")))
```

**Comment by oantolin** [comment] 2021-10-06 22:50
Note that for `$` I don't just tack on a `$`, because the last letter matches at the start of the last word, so instead we say "the rest of string is letters and numbers".

**Comment by minad** [comment] 2024-03-31 16:06
I think this issue can be closed? The issue is quite old and also mostly resolved by Omar's last comments. Right now we don't have plans to add further styles, but Orderless is sufficiently extensible as has been demonstrated.

**Closed by minad** 2024-03-31 16:06 UTC
